Cleaned up configuration settings

diff --git a/terraform b/terraform
--- a/terraform
+++ b/terraform
@@ -10,18 +10,30 @@ terraform_execute() {
 			INTERACTIVE="-it"
 			;;
 	esac
-	[[ ! -f $PLUGIN_CACHE_DIR_HOST ]] && mkdir -p $PLUGIN_CACHE_DIR_HOST
-	[[ ! -f $WORK_DIR_HOST ]] && mkdir -p $WORK_DIR_HOST
+	[[ ! -d $CONFIG_DIR ]] && \
+		echo "Config dir [$CONFIG_DIR] doesn't exist. Aborting..." && \
+		exit 1
+	[[ ! -f $CONFIG_DIR/terraform.tfrc ]] && \
+		"Config file [$CONFIG_DIR/terraform.tfrc] doesn't exist. Aborting..." && \
+		exit 1
+	[[ ! -d $LOG_DIR ]] && mkdir -r $LOG_DIR
+	[[ ! -d $DATA_DIR ]] && mkdir -p $DATA_DIR
+	[[ ! -d $PLUGIN_CACHE_DIR ]] && mkdir -p $PLUGIN_CACHE_DIR
 	echo ""
 	docker run \
 		$INTERACTIVE \
 		--rm \
-		-e TF_CLI_CONFIG_FILE=$TF_CLI_CONFIG_FILE \
-		-v $CONF_DIR_HOST/$TF_CLI_CONFIG_FILE:$CONF_DIR_CONTAINER/$TF_CLI_CONFIG_FILE \
-		-v $PLUGIN_CACHE_DIR_HOST:$PLUGIN_CACHE_DIR_CONTAINER:rw \
-		-v $WORK_DIR_HOST:$WORK_DIR_CONTAINER:rw \
+		-e TF_DATA_DIR=/var/terraform/data \
+		-e TF_CLI_CONFIG_FILE=/var/terraform/config/terraform.tfrc \
+		-e TF_LOG=$LOG_LEVEL \
+		-e TF_LOG_PATH=/var/terraform/log/terraform.log \
+		-v $WORK_DIR:/var/terraform/work:rw \
+		-v $CONFIG_DIR/terraform.tfrc:/var/terraform/config/terraform.tfrc \
+		-v $PLUGIN_CACHE_DIR:/var/terraform/plugin-cache:rw \
+		-v $DATA_DIR:/var/terraform/data:rw \
+		-v $LOG_DIR:/var/terraform/log:rw \
+		-v $AWS_CONFIG_DIR:/root/.aws:ro \
 		-v /var/run/docker.sock:/var/run/docker.sock \
-		-v $(pwd)/.aws:/root/.aws:ro \
 		$TERRAFORM_IMAGE $@
 	echo "" 
 }
@@ -34,7 +46,7 @@ ARGS="$@"
 
 case $CMD in
 	# Main commands
-	init|validate|plan|apply|destory)			;&
+	init|validate|plan|apply|destroy)			;&
 	# All other commans
 	console|fmt|force-unlock|get|graph|import|login)	;&
 	logout|output|providers|refresh|show|state|taint)	;&
