Updated to abort if "terraform.tfrc" doesn't exit

diff --git a/terraform b/terraform
--- a/terraform
+++ b/terraform
@@ -6,13 +6,17 @@ terraform_execute() {
 	local CMD=$1
 	local INTERACTIVE=""
 	case $CMD in
-		console) INTERACTIVE="-it" ;;
+		apply|destroy|console) INTERACTIVE="-it" ;;
 	esac
+	readonly WORK_DIR=$(pwd)
 	DATA_DIR=$WORK_DIR/tfdata/data
 	PLUGIN_CACHE_DIR=$WORK_DIR/tfdata/plugin-cache
 	LOG_DIR=$WORK_DIR/tfdata/log
-	MOUNT_TERRAFORM_TFRC_FILE=""
-	[[ -f terraform.tfrc ]] && MOUNT_TERRAFORM_TFRC_FILE="-v terraform.tfrc:/root/terraform.tfrc"
+	[[ ! -f terraform.tfrc ]] && \
+		echo "[terraform.tfrc] configuration file not found." && \
+		echo "Aborting..." && 
+		echo "" && \
+		exit 1
 	[[ ! -d $LOG_DIR ]] && mkdir -p $LOG_DIR
 	[[ ! -d $DATA_DIR ]] && mkdir -p $DATA_DIR
 	[[ ! -d $PLUGIN_CACHE_DIR ]] && mkdir -p $PLUGIN_CACHE_DIR
@@ -25,7 +29,7 @@ terraform_execute() {
 		-e TF_DATA_DIR=/root/data \
 		-e TF_LOG=$LOG_LEVEL \
 		-e TF_LOG_PATH=/root/log/terraform.log \
-		$MOUNT_TERRAFORM_TFRC_FILE \
+		-v $WORK_DIR/terraform.tfrc:/root/terraform.tfrc \
 		-v $WORK_DIR:/root/work:rw \
 		-v $DATA_DIR:/root/data:rw \
 		-v $LOG_DIR:/root/log:rw \
